In [1]:
import numpy as np

In [2]:
nums = np.array([1,2,3,4])
print(nums)

[1 2 3 4]


In [5]:
nums2 = nums.reshape(2,2)
print(nums2)

[[1 2]
 [3 4]]


In [10]:
nums3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(nums3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
