In [2]:
import numpy as np

In [5]:
# 브로드 캐스팅
nums = np.array([10,20,30,40,50])
print(nums)

[10 20 30 40 50]


In [7]:
nums2 = nums * 2
print(nums2)

[ 20  40  60  80 100]


In [10]:
nums3 = nums - 5
print(nums3)

[ 5 15 25 35 45]


In [12]:
data = np.column_stack(([10,20,30,40],[1,2,3,4],[100,200,300,400]))
print(data)

[[ 10   1 100]
 [ 20   2 200]
 [ 30   3 300]
 [ 40   4 400]]
